name: fleet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  # crop_your_image: ^0.6.0+1
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  # dot_navigation_bar: ^1.0.1+3
  # drag_and_drop_lists: ^0.3.2
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  # flutter_image_compress: ^1.0.0
  flutter_localizations:
    sdk: flutter
  # flutter_polyline_points: ^1.0.0
  freezed_annotation: ^0.14.3
  get_it: ^6.0.0
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.10
  google_maps_flutter_web: ^0.3.2

  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # image_picker: ^0.8.4+2
  intl: ^0.17.0
  location: ^4.3.0
  path_provider: ^2.0.1
  retry: ^3.1.0
  web_socket_channel: ^2.1.0
  sentry_flutter: ^6.2.1
  firebase_analytics: ^9.0.3
  firebase_performance: ^0.8.0+2
  firebase_crashlytics: ^2.4.3


dev_dependencies:
  build_runner: ^2.0.5
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  hive_generator:
    git:
      url: https://github.com/hivedb/hive.git
      ref: master
      path: hive_generator
  json_serializable: ^5.0.0
  lint: ^1.7.2
  lints: ^1.0.1
  mocktail: ^0.1.2
  test: ^1.16.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
